export const ACTION = {
  TOGGLE_SELECT: "TOGGLE_SELECT",
  TOGGLE_COMPLETE: "TOGGLE_COMPLETE",
  CREATE_TODO: "CREATE_TODO",
  DELETE_TODO: "DELETE_TODO",
  DELETE_SELECTED_TODO: "DELETE_SELECTED_TODO",
  DELETE_COMPLETED_TODO: "DELETE_COMPLETED_TODO",
  TOGGLE_FORM: "TOGGLE_FORM",
  CHANGE_VIEW: "CHANGE_VIEW",
  SET_FILTER: "SET_FILTER",
  RESET: "RESET",
};
